//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluetoothSample.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluetoothSample.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app shows all available Bluetooth devices near to the phone.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is ready....
        /// </summary>
        internal static string BluetoothIsReady {
            get {
                return ResourceManager.GetString("BluetoothIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth status.
        /// </summary>
        internal static string BluetoothStatus {
            get {
                return ResourceManager.GetString("BluetoothStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for devices.
        /// </summary>
        internal static string ScanForDevices {
            get {
                return ResourceManager.GetString("ScanForDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning devices.
        /// </summary>
        internal static string ScanningDevices {
            get {
                return ResourceManager.GetString("ScanningDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show devices.
        /// </summary>
        internal static string ShowDevices {
            get {
                return ResourceManager.GetString("ShowDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by RSSI.
        /// </summary>
        internal static string SortDevicesByRssi {
            get {
                return ResourceManager.GetString("SortDevicesByRssi", resourceCulture);
            }
        }
    }
}
